controller_list:
  - name: fake_sb_arm_controller
    type: position_controllers/JointGroupPositionControllers
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: sb_arm
    pose: home
